version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - '.:/var/www/mailer/'
    restart: always
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080